### ISSUE TITLE
Krunker Translation to Bahasa Indonesia (Indonesian) (v3.8.2)

### ISSUE THREAD

**Issue by ThatAKAGuy** [mty22/krunker.io-translations#105]
Hello, I would like to translate Krunker to Indonesian, since there are many players are from Indonesia. I'm afraid they won't understand English, so I'd do something amazing for them.

I'm a native speaker, bilingual in Indonesia and English, and I live and was born in Indonesia. And I know English very well, because I've been learning English since I was 2 years old. If I get approval to work on translating, I would do it ASAP.

Thank you.

My IGN: AKAkuma
Discord: 2succ # 6602

**Comment by mty22** [comment]
Hi,

Thanks for the interest. For now we will hold off on Bahasa.

We also have this issue here: https://github.com/mty22/krunker.io-translations/issues/76

We'll reach out to you on this if we go ahead.

Cheers.
