### ISSUE TITLE
Korean translate contribution.

### ISSUE THREAD

**Issue by xKyotani** [mty22/krunker.io-translations#116]
I can contribute to translate South Korean since I am a Korean who can speak the language very well.

**Comment by mty22** [comment]
Hi @xKyotani !

Keep an eye out in Krunker Bunker, specifically the translation project channel.

I post updates there when changes to Korean language comes out.

For now, check out this pull request: https://github.com/mty22/krunker.io-translations/pull/130

**Comment by pjhsjiim0913** [comment]
I can also contribute to translate Korean, because I use Korean language as my first language.
