### ISSUE TITLE
Malayalam Translation application

### ISSUE THREAD

**Issue by Css-debug** [mty22/krunker.io-translations#120]
We will be working on a team of 5

Translators

1) astro#1876
2) VK#8617
3) Reverb#9999

Checker / Reviewer

1) fredtron1001#5099 
2) AJVisuals#8336

We will keep in mind the rules and regulations and the consequences if we do not abide by them. 

Sincerely, 
Our Team

**Comment by mty22** [comment]
Hello.

For now, we will just stick with Hindi language as it's mostly spoken in India:

https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers_in_India

Thank you.
