### ISSUE TITLE
Krunker Czech translation

### ISSUE THREAD

**Issue by KamilMadera** [mty22/krunker.io-translations#125]
Hi! I would like to translate into Czech language. I'm a native speaker.
_I'm waiting for approval..._

**Comment by KamilMadera** [comment]
I'm working on it!

**Comment by mty22** [comment]
Hello.

Thanks for the interest. For now, we'd like to hold off on adding Czech language to the game.

While you are welcome to translate Krunker into Czech, you wouldn't be eligible for rewards unless the language is added to the game.

Thank you.

**Comment by FilaDanner** [comment]
Hello, would you by any chance consider adding Czech any time soon?
