### ISSUE TITLE
Danish language support

### ISSUE THREAD

**Issue by Jack-Borg** [mty22/krunker.io-translations#127]
Hi there

Native Danish speaker here. I would like to translate Krunker to Danish :)

**Comment by Sorte1** [comment]
I am also a native Danish speaker.

**Comment by CrafterlKrunker** [comment]
@Jack-Borg you are best

**Comment by Jack-Borg** [comment]
@Sorte1 contact me on discord Jack Borg#6360 and we can talk about working on it

**Comment by mty22** [comment]
Hi @Jack-Borg 

We currently have German (currently in-game) and Dutch (pending to be added) translated.

I'd need to check about feasibility on adding Danish based on player numbers before I can approve.

This doesn't mean you aren't able to translate into Danish, it just means that the language is not likely to be added and you wouldn't be eligible for KR rewards (unless approved).

Cheers.

**Comment by mty22** [comment]
Sorry for the delay. We will hold off on this language for now. If we add it in future, we'll re-open this thread.
