### ISSUE TITLE
Japanese language updates(v3.8.2)

### ISSUE THREAD

**Issue by Hiro527** [mty22/krunker.io-translations#129]

**Comment by Hiro527** [comment]
I'll work at [ja_JP](https://www.github.com/mty22/krunker.io-translations/tree/ja_JP/).

**Comment by mty22** [comment]
@Hiro527 no problems, just remember to rebase from `main` before you start working in your branch. Ping me if you have questions.

**Comment by Hiro527** [comment]
yeah ok i won't forget one more time
I've learned how to rebase completely(｡•̀ᴗ-)✧

**Comment by Hiro527** [comment]
#131
