### ISSUE TITLE
Japaneese Language Updates v2

### ISSUE THREAD

**Issue by BOBMLXIII** [mty22/krunker.io-translations#145]
I am living in japan right now and also born in japan so I want to be translator.

**Comment by mty22** [comment]
@BOBMLXIII これをチェックしてくれますか？ https://github.com/mty22/krunker.io-translations/pull/131 

もし問題があったら、上のPull Requestにコメントしてください！

**Comment by mty22** [comment]
https://github.com/mty22/krunker.io-translations/issues/129 dupe
