### ISSUE TITLE
Can we have [Traditional Chinese] in Krunker?

### ISSUE THREAD

**Issue by ProFrank9453** [mty22/krunker.io-translations#151]
We have Simplified Chinese in Krunker for the Chinese people.
But, we need a official language for Hong Kong, Macau, and Taiwan.
So, I think we need to have Traditional Chinese in Krunker.

**Comment by mty22** [comment]
https://github.com/mty22/krunker.io-translations/issues/49 duplicate

**Comment by mty22** [comment]
@ProFrank9453 there's a pull request active already:

https://github.com/mty22/krunker.io-translations/pull/138/files

Can you help by reviewing, please?
