### ISSUE TITLE
Krunker Translation to Urdu

### ISSUE THREAD

**Issue by abdulqadirwebdev** [mty22/krunker.io-translations#152]
I am going to be translating krunker into urdu, help would be appreciated :)

**Comment by VandyTweaks** [comment]
I can help surely :) I am working on it right now

**Comment by abdulqadirwebdev** [comment]
> I can help surely :) I am working on it right now

okay when are we going to be approved

**Comment by abdulqadirwebdev** [comment]
okay we should start then hope you know urdu :P

**Comment by abdulqadirwebdev** [comment]
Okay so how much are you willing to translate
200 lines?

**Comment by VandyTweaks** [comment]
yes I can translate that much 
after i have done that I will attach the js file here
