### ISSUE TITLE
Krunker translation to Chinese (Hong Kong)

### ISSUE THREAD

**Issue by Therealzz** [mty22/krunker.io-translations#157]
I would like to start a new project of the Krunker translation from EN to ZH-HK.
Similar localization strategy is also applied on Youtube providing 3 different localizations:
Chinese(Simplified), Chinese(Traditional) and Chinese(Hong Kong)
I think it will provide a better localization and experience for Hong Kong Krunker players if ZH-HK is also available.

I am about to work with vl#5058 and L.#9105, which are also locals and natives, on the project.
Discord: zzdev#6948

Past localization experience:
https://steamcommunity.com/sharedfiles/filedetails/?id=1774893492

**Comment by jackshallattack** [comment]
we has started one but it was closed, so idk anymore

**Comment by mty22** [comment]
Hey @jackshallattack and @Therealzz - please check this issue out: https://github.com/mty22/krunker.io-translations/issues/49

Reach out to those guys, they can work with you on this.
