### ISSUE TITLE
Indonesian (B.Indo / Bahasa Indonesia) Translation

### ISSUE THREAD

**Issue by Thanosisnub** [mty22/krunker.io-translations#196]

**Comment by Thanosisnub** [comment]
pls approve:)

**Comment by mty22** [comment]
Please.. please.. please.. read the README and use the search feature. 

Duplicate of https://github.com/mty22/krunker.io-translations/issues/105

**Comment by Thanosisnub** [comment]
k read it...holding off bahasa....inform me pls when working on it
