### ISSUE TITLE
Arabic language support

### ISSUE THREAD

**Issue by mty22** [mty22/krunker.io-translations#2]
Arabic is written and read from right to left

Sample translation of the following menu:

![image](https://user-images.githubusercontent.com/2951231/111618804-ea934c00-8838-11eb-9200-712d5ea23fb7.png)

```
settings.gameplay.header طريقه اللعب
settings.gameplay.slidCont FPS انزلاق بدون
settings.gameplay.sensitivityX X حساسيه مستوى
settings.gameplay.sensitivityY Y حساسيه مستوى
settings.gameplay.aimsensX X حساسيه تصويب
settings.gameplay.aimsensY Y حساسيه تصويب
settings.gameplay.challenge طور التحدي
settings.gameplay.invert Y عكس المحور
settings.gameplay.onkillS On Kill
settings.gameplay.scrollDir اتجاه التمرير
```

Need to confirm if this is supported or not in game, or if it will just be grammatically incorrect after rendering.

Submitted on behalf of: https://www.twitch.tv/clownflsh

**Comment by fich-c** [comment]
<html dir="rtl" lang="ar">
<head>
<meta charset="utf-8">

**Comment by mty22** [comment]
@fich-c sorry, you need to explain what you are trying to point out.

**Comment by mty22** [comment]
Can't do this one. =(

**Comment by mty22** [comment]
If any native Arabic speaker could reach out to me on Discord (frzn#1030) to discuss, that'd be appreciated!

**Comment by mty22** [comment]
```[10:22 PM] Clownfish: settings.editing.health.high لون الصحه العاليه
settings.editing.health.low لون الصحه المنخفضه
settings.editing.speedLines خطوط التسارع
settings.editing.spdLinesCol لون خطوط التسارع
settings.editing.score.color ظهور لون النتيجه
settings.editing.score.show ظهور النتيجه المنبثقه
settings.editing.score.scale حجم النتيجه المنبثقه
settings.editing.score.shadow ظل النتيجه المنبثقه
settings.editing.scoreOffX Xإزاحة النتيجه المنبثقه 
settings.editing.scoreOffY Yإزاحة النقاط المنبثقة 
settings.editing.prog.color لون شريط التقدم
settings.editing.prog.opacity تعتيم شريط التقدم
settings.editing.prog.scale حجم شريط التقدم
settings.editing.prog.shadow ظل شريط التقدم
settings.editing.progOffX X ازاحه شريط التقدم
settings.editing.progOffY Yازاحه شريط التقدم 
settings.editing.progRot دوران شريط التقدم
[10:25 PM] Clownfish: done```

LEFT -> RIGHT grammar. Plausible.

**Comment by uvaizfaisel** [comment]
settings.gameplay.header طريقه اللعب 
thareeqath-ul-alleab actually means way of playing 

i guess إعدادات اللعب will be more accurate which means the settings or the configuration of game play

**Comment by uvaizfaisel** [comment]
in "settings.gameplay.challenge طور التحدي"
طور التحدي just means "turn on the challenge" and if we look some other way, we get many other inaccurate meanings
I suggest using طريقة التحدي, which perfectly translates to challenge mode

**Comment by uvaizfaisel** [comment]
the whole Arabic language is based on opinions, so I must highlight that the other contributor also should agree with me, to finalize that my arguments are correct, even though I'm a semi-native Arabic speaker and studies in an English medium school my language subject is Arabic, so I could help further on correction, also I'm glad to help the krunker community :]

**Comment by fich-c** [comment]
> in "settings.gameplay.challenge طور التحدي"
> طور التحدي just means "turn on the challenge" and if we look some other way, we get many other inaccurate meanings
> I suggest using طريقة التحدي / التحدي طريقه, which perfectly translates to challenge mode/challenging way
well, طور التحدي accurately means challenge mode. the way you translated it is طريقه التحدي which means challenge way/challenging.

**Comment by fich-c** [comment]
> the whole Arabic language is based on opinions, so I must highlight that the other contributor also should agree with me, to finalize that my arguments are correct, even though I'm a semi-native Arabic speaker and studies in an English medium school my language subject is Arabic, so I could help further on correction, also I'm glad to help the krunker community :]

yes, some of the Arabic language is based on opinions, but not all opinions are right. I have experience in translation mainly website translating and little experience in game translation. You are pretty good for a semi-native Arab, so I would love to work with you 😄 You also need to learn/know Classical Arabic, which is the main Arabic type used for translation and text.

**Comment by uvaizfaisel** [comment]
> > in "settings.gameplay.challenge طور التحدي"
> > طور التحدي just means "turn on the challenge" and if we look some other way, we get many other inaccurate meanings
> > I suggest using طريقة التحدي / التحدي طريقه, which perfectly translates to challenge mode/challenging way
> 
> well, طور التحدي accurately means challenge mode. the way you translated it is طريقه التحدي which means challenge way/challenging.

yeah,  I will ask to my Arabic sir and let you know about it shortly.

**Comment by uvaizfaisel** [comment]
> > the whole Arabic language is based on opinions, so I must highlight that the other contributor also should agree with me, to finalize that my arguments are correct, even though I'm a semi-native Arabic speaker and studies in an English medium school my language subject is Arabic, so I could help further on correction, also I'm glad to help the krunker community :]
> 
> yes, some of the Arabic language is based on opinions, but not all opinions are right. I have experience in translation mainly website translating and little experience in game translation. You are pretty good for a semi-native Arab, so I would love to work with you 😄 You also need to learn/know Classical Arabic, which is the main Arabic type used for translation and text. also if you want to discuss more Discord:Clownfish#9724

I don't speak Arabic a lot at my home, though I'm an Arabic student, so yeah I know about its grammar and related subjects 
, I guess we don't have to talk more about it because, yeah that was the only two mistakes I found, now the real problem is making its way to the game.

**Comment by fich-c** [comment]
> > > the whole Arabic language is based on opinions, so I must highlight that the other contributor also should agree with me, to finalize that my arguments are correct, even though I'm a semi-native Arabic speaker and studies in an English medium school my language subject is Arabic, so I could help further on correction, also I'm glad to help the krunker community :]
> > 
> > 
> > yes, some of the Arabic language is based on opinions, but not all opinions are right. I have experience in translation mainly website translating and little experience in game translation. You are pretty good for a semi-native Arab, so I would love to work with you 😄 You also need to learn/know Classical Arabic, which is the main Arabic type used for translation and text. also if you want to discuss more Discord:Clownfish#9724
> 
> I don't speak Arabic a lot at my home, though I'm an Arabic student, so yeah I know about its grammar and related subjects
> , I guess we don't have to talk more about it because, yeah that was the only two mistakes I found, now the real problem is making its way to the game.

I appreciate your help 😊. And may i ask whats your naitve language cause it might help?

**Comment by uvaizfaisel** [comment]
> > > > the whole Arabic language is based on opinions, so I must highlight that the other contributor also should agree with me, to finalize that my arguments are correct, even though I'm a semi-native Arabic speaker and studies in an English medium school my language subject is Arabic, so I could help further on correction, also I'm glad to help the krunker community :]
> > > 
> > > 
> > > yes, some of the Arabic language is based on opinions, but not all opinions are right. I have experience in translation mainly website translating and little experience in game translation. You are pretty good for a semi-native Arab, so I would love to work with you 😄 You also need to learn/know Classical Arabic, which is the main Arabic type used for translation and text. also if you want to discuss more Discord:Clownfish#9724
> > 
> > 
> > I don't speak Arabic a lot at my home, though I'm an Arabic student, so yeah I know about its grammar and related subjects
> > , I guess we don't have to talk more about it because, yeah that was the only two mistakes I found, now the real problem is making its way to the game.
> 
> I appreciate your help 😊. And may i ask whats your naitve language cause it might help?

well , as my mother is from India,  my true native language is Malayalam

**Comment by fich-c** [comment]
> > > > > the whole Arabic language is based on opinions, so I must highlight that the other contributor also should agree with me, to finalize that my arguments are correct, even though I'm a semi-native Arabic speaker and studies in an English medium school my language subject is Arabic, so I could help further on correction, also I'm glad to help the krunker community :]
> > > > 
> > > > 
> > > > yes, some of the Arabic language is based on opinions, but not all opinions are right. I have experience in translation mainly website translating and little experience in game translation. You are pretty good for a semi-native Arab, so I would love to work with you 😄 You also need to learn/know Classical Arabic, which is the main Arabic type used for translation and text. also if you want to discuss more Discord:Clownfish#9724
> > > 
> > > 
> > > I don't speak Arabic a lot at my home, though I'm an Arabic student, so yeah I know about its grammar and related subjects
> > > , I guess we don't have to talk more about it because, yeah that was the only two mistakes I found, now the real problem is making its way to the game.
> > 
> > 
> > I appreciate your help 😊. And may i ask whats your naitve language cause it might help?
> 
> well , as my mother is from India, my true native language is Malayalam

Try translating krunker to Malayalam! It will help add more languages to the game!

**Comment by uvaizfaisel** [comment]
> > > > > > the whole Arabic language is based on opinions, so I must highlight that the other contributor also should agree with me, to finalize that my arguments are correct, even though I'm a semi-native Arabic speaker and studies in an English medium school my language subject is Arabic, so I could help further on correction, also I'm glad to help the krunker community :]
> > > > > 
> > > > > 
> > > > > yes, some of the Arabic language is based on opinions, but not all opinions are right. I have experience in translation mainly website translating and little experience in game translation. You are pretty good for a semi-native Arab, so I would love to work with you 😄 You also need to learn/know Classical Arabic, which is the main Arabic type used for translation and text. also if you want to discuss more Discord:Clownfish#9724
> > > > 
> > > > 
> > > > I don't speak Arabic a lot at my home, though I'm an Arabic student, so yeah I know about its grammar and related subjects
> > > > , I guess we don't have to talk more about it because, yeah that was the only two mistakes I found, now the real problem is making its way to the game.
> > > 
> > > 
> > > I appreciate your help 😊. And may i ask whats your naitve language cause it might help?
> > 
> > 
> > well , as my mother is from India, my true native language is Malayalam
> 
> Try translating krunker to Malayalam! It will help add more languages to the game!

alright, does that mean i should stop by here, or inquire about the correction mentioned above to my sir?

**Comment by fich-c** [comment]
> > > > > > > the whole Arabic language is based on opinions, so I must highlight that the other contributor also should agree with me, to finalize that my arguments are correct, even though I'm a semi-native Arabic speaker and studies in an English medium school my language subject is Arabic, so I could help further on correction, also I'm glad to help the krunker community :]
> > > > > > 
> > > > > > 
> > > > > > yes, some of the Arabic language is based on opinions, but not all opinions are right. I have experience in translation mainly website translating and little experience in game translation. You are pretty good for a semi-native Arab, so I would love to work with you 😄 You also need to learn/know Classical Arabic, which is the main Arabic type used for translation and text. also if you want to discuss more Discord:Clownfish#9724
> > > > > 
> > > > > 
> > > > > I don't speak Arabic a lot at my home, though I'm an Arabic student, so yeah I know about its grammar and related subjects
> > > > > , I guess we don't have to talk more about it because, yeah that was the only two mistakes I found, now the real problem is making its way to the game.
> > > > 
> > > > 
> > > > I appreciate your help 😊. And may i ask whats your naitve language cause it might help?
> > > 
> > > 
> > > well , as my mother is from India, my true native language is Malayalam
> > 
> > Try translating krunker to Malayalam! It will help add more languages to the game!
> 
> alright, does that mean i should stop by here, or enquire about the correction mentioned above to my sir?
No. I meant translate what is easier to you and likely not to get some mistakes in since you are still learning arabic and that great! i appreciate every help you've done even if its worng. 👍

**Comment by Wreck-It-Felix** [comment]
> > > > > > > > the whole Arabic language is based on opinions, so I must highlight that the other contributor also should agree with me, to finalize that my arguments are correct, even though I'm a semi-native Arabic speaker and studies in an English medium school my language subject is Arabic, so I could help further on correction, also I'm glad to help the krunker community :]
> > > > > > > 
> > > > > > > 
> > > > > > > yes, some of the Arabic language is based on opinions, but not all opinions are right. I have experience in translation mainly website translating and little experience in game translation. You are pretty good for a semi-native Arab, so I would love to work with you 😄 You also need to learn/know Classical Arabic, which is the main Arabic type used for translation and text. also if you want to discuss more Discord:Clownfish#9724
> > > > > > 
> > > > > > 
> > > > > > I don't speak Arabic a lot at my home, though I'm an Arabic student, so yeah I know about its grammar and related subjects
> > > > > > , I guess we don't have to talk more about it because, yeah that was the only two mistakes I found, now the real problem is making its way to the game.
> > > > > 
> > > > > 
> > > > > I appreciate your help 😊. And may i ask whats your naitve language cause it might help?
> > > > 
> > > > 
> > > > well , as my mother is from India, my true native language is Malayalam
> > > 
> > > 
> > > Try translating krunker to Malayalam! It will help add more languages to the game!
> > 
> > 
> > alright, does that mean i should stop by here, or enquire about the correction mentioned above to my sir?
> 
> No. I meant translate what is easier to you and likely not to get some mistakes in since you are still learning arabic and that's great! i appreciate every help you've done even if its worng. 👍

Hey guys, I can help you if you want in contributing to write Arabic, high school native arabic speaker here

**Comment by ziad-Ro** [comment]
> > > > > > > > > the whole Arabic language is based on opinions, so I must highlight that the other contributor also should agree with me, to finalize that my arguments are correct, even though I'm a semi-native Arabic speaker and studies in an English medium school my language subject is Arabic, so I could help further on correction, also I'm glad to help the krunker community :]
> > > > > > > > 
> > > > > > > > 
> > > > > > > > yes, some of the Arabic language is based on opinions, but not all opinions are right. I have experience in translation mainly website translating and little experience in game translation. You are pretty good for a semi-native Arab, so I would love to work with you 😄 You also need to learn/know Classical Arabic, which is the main Arabic type used for translation and text. also if you want to discuss more Discord:Clownfish#9724
> > > > > > > 
> > > > > > > 
> > > > > > > I don't speak Arabic a lot at my home, though I'm an Arabic student, so yeah I know about its grammar and related subjects
> > > > > > > , I guess we don't have to talk more about it because, yeah that was the only two mistakes I found, now the real problem is making its way to the game.
> > > > > > 
> > > > > > 
> > > > > > I appreciate your help 😊. And may i ask whats your naitve language cause it might help?
> > > > > 
> > > > > 
> > > > > well , as my mother is from India, my true native language is Malayalam
> > > > 
> > > > 
> > > > Try translating krunker to Malayalam! It will help add more languages to the game!
> > > 
> > > 
> > > alright, does that mean i should stop by here, or enquire about the correction mentioned above to my sir?
> > 
> > 
> > No. I meant translate what is easier to you and likely not to get some mistakes in since you are still learning arabic and that's great! i appreciate every help you've done even if its worng. 👍
> 
> Hey guys, I can help you if you want in contributing to write Arabic, high school native arabic speaker here

i can help too. Arabic native speaker too!

**Comment by ziad-Ro** [comment]
> settings.gameplay.header طريقه اللعب
> thareeqath-ul-alleab actually means way of playing
> 
> i guess إعدادات اللعب will be more accurate which means the settings or the configuration of game play

 yes its accurate but I think the contributor put طريقه اللعب cause of the text box إعدادات اللعب wont work out.

**Comment by ziad-Ro** [comment]
is the arabic translation finished is there anything that i can help with?

**Comment by 8-10krunker** [comment]
Hey, id like to help with arabic if theres anything left to do :}

**Comment by mty22** [comment]
Going to close this one off since it doesn't seem to be possible with the left to right syntax.
