### ISSUE TITLE
Krunker Translate to Traditional Chinese

### ISSUE THREAD

**Issue by Vylerria** [mty22/krunker.io-translations#204]

**Comment by Vylerria** [comment]
i have completed the translation, should i submit it and where should i do that?

**Comment by mty22** [comment]
Hi @Vylerria - feel free to check the README file ([https://github.com/mty22/krunker.io-translations/blob/main/README.md)

Thank you.

**Comment by mty22** [comment]
In short, submit a pull request for review :)
