### ISSUE TITLE
Russian language support (v3.8.1)

### ISSUE THREAD

**Issue by mty22** [mty22/krunker.io-translations#21]
Need to add Russian language support!

**Comment by realTiXoNyA** [comment]
Hello, I would like to try to do this task)

**Comment by hellcatsrt** [comment]
I would also love to help with this task!

**Comment by coeg701** [comment]
Hello, I would like to help with the translation as well!

**Comment by Yurikan4ik** [comment]
Hello! I would like to help with translation too

**Comment by mty22** [comment]
@realTiXoNyA @hellcatsrt @coeg701 @Yurikan4ik go ahead! please work together and make it happen :)

**Comment by realTiXoNyA** [comment]
ok, the work on the two translations is in full swing. We teamed up with @Yurikan4ik and  @coeg701 as a team

**Comment by realTiXoNyA** [comment]
I uploaded ru.js do you see the file? if not, please tell me where to upload it)

**Comment by hellcatsrt** [comment]
yes I see it, thank you

**Comment by ligmabots** [comment]
hey @mty22 can I help with russian translation, or if it's done I can verify it.
