### ISSUE TITLE
nl.js updates (v4.2.2)

### ISSUE THREAD

**Issue by TrafficDonkey** [mty22/krunker.io-translations#219]
I want to work on this project with somebody else
 https://github.com/mty22/krunker.io-translations/pull/207/commits/5caa17cf637e2b1aaf93f346ee0e0fa37ff012cd

**Comment by mty22** [comment]
Go for it.

**Comment by nickauthentic** [comment]
you can work with me. incase I'm not there or don't have time

**Comment by mty22** [comment]
hi @TrafficDonkey - any updates on this?

**Comment by mty22** [comment]
@nickauthentic is assigned to this now

**Comment by jodiejomensen** [comment]
Hi there need  any help? DM me on discord flipbait#7801
