### ISSUE TITLE
[Japanese] Fixing incomplete translations and translations that don't match the guide.

### ISSUE THREAD

**Issue by peyang-Celeron** [mty22/krunker.io-translations#220]
I'm in charge of translating a large game server.
I found a translation of Krunker that doesn't match the ["JTF Style Guide for Translators Working into Japanese"](https://www.jtf.jp/pdf/jtf_style_guide.pdf), can I fix it?
Also, there are some incomplete translations and I would like to publish a PR with them corrected.
Discord: `Peyang#0001`
Krunker: `peyang`

**Comment by mty22** [comment]
@Hiro527さん、 どう思いますか？

**Comment by Hiro527** [comment]
> 
> 
> I'm in charge of translating a large game server.
> I found a translation of Krunker that doesn't match the ["JTF Style Guide for Translators Working into Japanese"](https://www.jtf.jp/pdf/jtf_style_guide.pdf), can I fix it?
> Also, there are some incomplete translations and I would like to publish a PR with them corrected.
> Discord: `Peyang#0001`
> Krunker: `peyang`

今年に入ってから翻訳を担当しているHiroと申します。

確かに不完全だったりする部分が多々あることは前々から承知しています。
ただ、ゲームというものの性質上UIに多少なりとも合わせなければいけない部分があるので、長くなる表現を避けていたりするのが現状です。その結果わかりにくかったり意味は通るけど少し不自然、不完全なものになってしまっています。
翻訳の改善には賛成をしますがそのガイドがゲームの翻訳向けではないことから起こるデメリットが少し気になってしまいます。
また、どのような部分がJTFのガイドに即していないかなど具体的に教示していただけると幸いです。

**Comment by peyang-Celeron** [comment]
> > I'm in charge of translating a large game server.
> > I found a translation of Krunker that doesn't match the ["JTF Style Guide for Translators Working into Japanese"](https://www.jtf.jp/pdf/jtf_style_guide.pdf), can I fix it?
> > Also, there are some incomplete translations and I would like to publish a PR with them corrected.
> > Discord: `Peyang#0001`
> > Krunker: `peyang`
> 
> @peyang-Celeron さん、こんにちは。
> 今年に入ってから翻訳を担当しているHiroと申します。
> 
> 確かに不完全だったりする部分が多々あることは前々から承知しています。
> ただ、ゲームというものの性質上UIに多少なりとも合わせなければいけない部分があるので、長くなる表現を避けていたりするのが現状です。その結果わかりにくかったり意味は通るけど少し不自然、不完全なものになってしまっています。
> 翻訳の改善には賛成をしますがそのガイドがゲームの翻訳向けではないことから起こるデメリットが少し気になってしまいます。「正しい日本語」にするのか「ゲーム内でわかりやすく、見た目も崩れない日本語」にするのか、どっちが重要かという話にもつながってくると思います。
> また、どのような部分がJTFのガイドに即していないかなど具体的にご教示いただけると幸いです。

レビューありがとうございます。  
JTFのガイドに即していない点としては、「!」「?」「()」が全角でない点や、末尾の「er」に対する長音が統一されていない(「フィルタ」「ブラウザ」)点、「でき - る」等を「出来 - る」と表記している点などが挙げられます。
また、JTFガイドには記載されておりませんが「...」を「…」\(三点リーダー\)と表記すると見た目の改善を行えるかもしれません。
参考：
![image](https://user-images.githubusercontent.com/42040068/126961180-1eabbde7-4398-4fb9-821d-31d19d803bac.png)
![image](https://user-images.githubusercontent.com/42040068/126961219-222da83e-cfbe-4c2f-9ae5-3d07471e81bb.png)

重箱の隅をつつくようで申し訳ございません。

**Comment by Hiro527** [comment]
> 
> レビューありがとうございます。  
> JTFのガイドに即していない点としては、「!」「?」「()」が全角でない点[*1](https://github.com/mty22/krunker.io-translations/blob/7c1f4122dcb11166c8ef931c71f79b19fb39b488/jp.js#L757)[ *2](https://github.com/mty22/krunker.io-translations/blob/7c1f4122dcb11166c8ef931c71f79b19fb39b488/jp.js#L628)や、末尾の「er」に対する長音が統一されていない(「フィルタ」「ブラウザ」)点、「でき - る」等を「出来 - る」と表記している点[*](https://github.com/mty22/krunker.io-translations/blob/7c1f4122dcb11166c8ef931c71f79b19fb39b488/jp.js#L758)などが挙げられます。

記号を半角に揃えているのは英語UIとの統一のために意図的に行っています。Krunkerは一部のUIの翻訳が追いつかないなどの理由で英語の部分が少し残っていることがあるため全角にしてしまうと見た目が崩れるかもしれないためです。
erに対する長音の統一が取れていないのはご指摘のとおりです。現状、過去の翻訳者が翻訳した部分などと統一が取れていません。

> また、JTFガイドには記載されておりませんが「...」を「…」\(三点リーダー\)と表記すると見た目の改善を行えるかもしれません[*](https://github.com/mty22/krunker.io-translations/blob/7c1f4122dcb11166c8ef931c71f79b19fb39b488/jp.js#L698)。
> 参考：
> ![image](https://user-images.githubusercontent.com/42040068/126961180-1eabbde7-4398-4fb9-821d-31d19d803bac.png)
> ![image](https://user-images.githubusercontent.com/42040068/126961219-222da83e-cfbe-4c2f-9ae5-3d07471e81bb.png)
> 
> 重箱の隅をつつくようで申し訳ございません。
> 

三点リーダに関してはフォントの対応状況がバラバラなことがあるためピリオドで表現しています。リソーススワッパーやModによりフォントが変えられるため安全策を取っています。

改善ができる部分はたくさんあると思うので、もし必要でしたら僕もお手伝いさせていただきたいです。よろしくお願いします。

**Comment by peyang-Celeron** [comment]
>記号を半角に揃えているのは英語UIとの統一のために意図的に行っています。Krunkerは一部のUIの翻訳が追いつかないなどの理由で英語の部分が少し残っていることがあるため全角にしてしまうと見た目が崩れるかもしれないためです。
> 三点リーダに関してはフォントの対応状況がバラバラなことがあるためピリオドで表現しています。リソーススワッパーやModによりフォントが変えられるため安全策を取っています。

了解いたしました。迅速なご対応をいただきありがとうございました。

>erに対する長音の統一が取れていないのはご指摘のとおりです。現状、過去の翻訳者が翻訳した部分などと統一が取れていません。
> 改善ができる部分はたくさんあると思うので、もし必要でしたら僕もお手伝いさせていただきたいです。よろしくお願いします。

とりあえずerに対する長音の統一 に関するPRをのちほど開いても宜しいでしょうか？
また、その際はレビューをお願いしたく存じます。

**Comment by Hiro527** [comment]
@peyang-Celeron 
了解です。お時間のあるときに是非お願いします。
