### ISSUE TITLE
hi.js update v4.09

### ISSUE THREAD

**Issue by Inspire-24** [mty22/krunker.io-translations#221]
working on this

**Comment by mty22** [comment]
Go for it.

**Comment by BluZed** [comment]
Can I help you in any sort of way? I would like to help in improvement of this delightful game. I am fluent in Hindi. :D

**Comment by BluZed** [comment]
So if yes, you can add me at discord- BluZed#9946

**Comment by BluZed** [comment]
Help wanted? Can I have permission?

**Comment by BluZed** [comment]
Can I get approval for help?

**Comment by mty22** [comment]
@BluZed reach out to @Inspire-24 and see if you can team up and work on it.

**Comment by mty22** [comment]
@BluZed actually, have a look at this pull request: https://github.com/mty22/krunker.io-translations/pull/230/files and review please!

**Comment by BluZed** [comment]
@mty22 Sure
