### ISSUE TITLE
[Italian] Issue with "player.killstreak" string

### ISSUE THREAD

**Issue by MrGira** [mty22/krunker.io-translations#227]
I found two problems with the ```player.killstreak``` string:

- When the player does a killstreak, the message doesn't make sense since the placeholder ```{0}``` gives the output "_You're_".

![image](https://user-images.githubusercontent.com/82208243/127369121-32d19703-65b1-431c-b5a0-b4a3edd9aeb3.png)

- When an opponent is on a killstreak, the message doesn't make sense since the same aforementioned placeholder includes the verb "_is_" in this case.

![image](https://user-images.githubusercontent.com/82208243/127369503-c9488dcc-d521-4683-9eb1-33fbc78a286c.png)

**Comment by mty22** [comment]
Ah yes, this is a known issue. should revert it all back to English.

**Comment by mty22** [comment]
leaving open as I need to update README.md

**Comment by mty22** [comment]
related https://github.com/mty22/krunker.io-translations/issues/1
