### ISSUE TITLE
Krunker Bangla or Bengali translation.

### ISSUE THREAD

**Issue by BD-T** [mty22/krunker.io-translations#249]
I just want to say I want to translate Krunker In Bangla/Bengali language, don't give me a duplicate tag. Ik I am duplicating from the real but I just want to say we need the Bengali/Bangla language. In Krunker there has 1500 players who are Bengali and talks in Bangla/Bengali and they play Krunker, so I request to translate Krunker into the Bengali/Bangla language. Waiting for approval, My discord: BΛNGLΛDΞSH 💦#9494

**Comment by mty22** [comment]
hello --

please use the search feature before opening a new request

https://github.com/mty22/krunker.io-translations/issues?q=Bengali
https://github.com/mty22/krunker.io-translations/issues/38

**Comment by BD-T** [comment]
> hello --
> 
> please use the search feature before opening a new request
> 
> https://github.com/mty22/krunker.io-translations/issues?q=Bengali
> #38


> hello --
> 
> please use the search feature before opening a new request
> 
> https://github.com/mty22/krunker.io-translations/issues?q=Bengali
> #38

Bro, i saw that i just open a new issue because i need to inform you about the importance of adding Bengali/Bangla language. And the other guys that open Bengali/Bangla language issues they don't mention the importance.
