### ISSUE TITLE
Italian Translation Request

### ISSUE THREAD

**Issue by MrGira** [mty22/krunker.io-translations#25]
Hi, we are opening this issue to ask if it is possible to translate krunker into Italian.  My colleague Hiroo and I would be interested in the project.

Discord: MrGira# 0999

**Comment by mty22** [comment]
Hey! Thanks for the interest, will get back to you on this.

**Comment by gio404gio** [comment]
HI, I would be interested to partecipate  the project. Im from Italy.
Discord: scusa#9624

**Comment by gio404gio** [comment]
thanks, keep me update.
GD

Il giorno ven 30 apr 2021 alle ore 17:14 Matt Taylor <
***@***.***> ha scritto:

**Comment by mty22** [comment]
@MrGira Italian is approved - you are in charge of forming a team of native Italian speakers.

https://raw.githubusercontent.com/mty22/krunker.io-translations/main/en.js

Another player ( @pifferaioarkyno )  did start working on it, so you are welcome to continue work from their contributions so far:

https://github.com/mty22/krunker.io-translations/pull/122/files

https://meldmerge.org/ -- this tool is useful for comparing old/new.

Sorry for the delay!

**Comment by gio404gio** [comment]
np ill start working on it. Thanks for the news and to accepted me.
Have a good day

Il giorno dom 9 mag 2021 alle ore 09:25 Matt Taylor <
***@***.***> ha scritto:

**Comment by MrGira** [comment]
Thank you @mty22. We will review @pifferaioarkyno work and proceed with translation as soon as possible. Please @gio404gio don't start working on your own, we are already organizing

**Comment by gio404gio** [comment]
ok understood, im in contact with MrGira, he will tell me how to properly
work with them. Thanks again for the possibility to work with u guys.

Il giorno dom 9 mag 2021 alle ore 09:40 MrGira ***@***.***>
ha scritto:

**Comment by BatMatt71** [comment]
Hello. I saw this issue and I was wondering if help is wanted. I would gladly help

**Comment by 8-10krunker** [comment]
Hi, i was wondering if i could help with this project. I would be happy to help

**Comment by mty22** [comment]
This one is complete~

Check for future updates~

**Comment by BatMatt71** [comment]
Oh

**Comment by BatMatt71** [comment]
:(

**Comment by GiammyRL** [comment]
I wanted to help but I guess it's too late!
