### ISSUE TITLE
Approval to work on hi.js

### ISSUE THREAD

**Issue by Crazyboi8382** [mty22/krunker.io-translations#264]
i found some stuff in hi.js that isnt translated to hindi so could i possibly be given approval to work on it?

**Comment by 0v0katai** [comment]
@Crazyboi8382 Suggest your changes by commenting there with line and corresponding suggestion

**Comment by mty22** [comment]
Go for it.

**Comment by mty22** [comment]
@Crazyboi8382 any updates?

**Comment by mty22** [comment]
I consider that @Crazyboi8382 has abandoned this. Anyone is free to take over.
