### ISSUE TITLE
Greek translation for krunker

### ISSUE THREAD

**Issue by emmanuel1233** [mty22/krunker.io-translations#267]
I've seen some Greek players out there so I thought if I could help with the translation.

**Comment by emmanuel1233** [comment]
my discord tag is onlyme#3899

**Comment by xristosTUBE** [comment]
i would like to work with emmanuel1233 with the greek translation! my discord tag is: Tr1x#5917

**Comment by mty22** [comment]
Will review.

**Comment by Gerardo2704** [comment]
Hello I would also like to help with translating, Greek is my second language.

**Comment by mty22** [comment]
See https://github.com/mty22/krunker.io-translations/issues/43
