### ISSUE TITLE
Hungarian translation

### ISSUE THREAD

**Issue by Eglor01** [mty22/krunker.io-translations#279]
Hello Krunker team,

I'm a native hungarian speaker and I would be Interested in making a hungarian translation for krunker. I have exprience whit translting a cuple lines of text for the minecraft launcher. If you were to let me translate then please contac me on my disocrd at EglorASD#2122

looking forward to translating Balázs.

**Comment by mty22** [comment]
Hungarian is currently WIP. Although it won't be added to the game for the short term.

See https://github.com/mty22/krunker.io-translations/blob/main/work-in-progress/hu.js
