### ISSUE TITLE
[v5.4.1/jp.js] Grammar issues

### ISSUE THREAD

**Issue by Hiro527** [mty22/krunker.io-translations#296]
I found that there are some grammar issues in sentences for challenges.
For example:
```
chall.name.hs Get {0} headshots {1}
```
The sentence above will be like "Get 50 headshots in Sandstorm". "50" fills {0} and "in Sandstorm" fills {1}. But in Japanese, it should be like "Sandstormで50回ヘッドショット". "Sandstorm" will be {0} so that "50" will be {1}. There's differences that can't be resolved easily between English and Japanese. We've talked about similar issues and we've left it as it as so that I'll open new pr that doesn't include changes for this section.

**Comment by mty22** [comment]
This issue is systemic. I'll have a chat with the devs about it when time permits. For now, best to leave it in English.

**Comment by mty22** [comment]
added to https://github.com/mty22/krunker.io-translations/blob/main/KNOWN_ISSUES.md

**Comment by mty22** [comment]
This is confirmed, and won't be changed anytime soon.

the `{1}` variable also may appear as:
`on X` (map)
`with X Weapon` (gun)
