### ISSUE TITLE
Finnish language updates (v3.8.1)

### ISSUE THREAD

**Issue by mty22** [mty22/krunker.io-translations#30]
Finnish: https://github.com/mty22/krunker.io-translations/commit/25992fdd7fc11edd215acf19325d689d92ce673e

**Comment by mty22** [comment]
reached out to Jypa on this one

**Comment by DevOjas** [comment]
i can try if ya want

**Comment by mty22** [comment]
@DevOjas can you please have a look at @DefinitelyJypa 's changes here: https://github.com/mty22/krunker.io-translations/pull/236

I'll send you KR upon completion.

**Comment by mty22** [comment]
Anyone is good!

**Comment by SuomiLammas25** [comment]
If it's still not done I can do it

**Comment by pyrtsa-cell** [comment]
What can I do to help on this?

**Comment by mty22** [comment]
@pyrtsa-cell check out the README.md file !
