### ISSUE TITLE
Translating Krunker Into Lingala

### ISSUE THREAD

**Issue by ItDoBeSarkis** [mty22/krunker.io-translations#300]
Hey, Id be happy to translate krunker into lingala,

I do want to clarify, I am NOT the person translating this, but rather representing a friend who is happy to translate the game, 
My friend does want to stay anonymous, which is why I am the one submitting the issue, and will be representing him myself. Think about us as a team,

Discord: Sarkis#6170

**Comment by mty22** [comment]
Thanks for the interest! For now we will not translate Krunker into Lingala language.

If demand permits, we'll re-review and open this again.

https://en.wikipedia.org/wiki/Lingala
