### ISSUE TITLE
French language updates (v3.8.1)

### ISSUE THREAD

**Issue by mty22** [mty22/krunker.io-translations#31]
French: https://github.com/mty22/krunker.io-translations/commit/82edf20a2b258c21eec1ff06d609b6953bbb63a6

**Comment by mty22** [comment]
This is being worked on by @NonoLePoulet in PR: https://github.com/mty22/krunker.io-translations/pull/59

**Comment by NonoLePoulet** [comment]
Yes

**Comment by NonoLePoulet** [comment]
I've made a push request

**Comment by VercroXft** [comment]
I've made a pull request with more than 700 modif
