### ISSUE TITLE
Simplified Chinese language updates (v3.8.1)

### ISSUE THREAD

**Issue by mty22** [mty22/krunker.io-translations#33]
Simplified Chinese: https://github.com/mty22/krunker.io-translations/commit/e89b8249bf15c6038cc46c506223d0791672aae1

**Comment by Awesome-Boy-001** [comment]
Hello; I can help with the Simplified Chinese language update.

**Comment by Awesome-Boy-001** [comment]
I'm currently working on Chinese, Simplified version of translation.

Discord ID: Awesome_Boy#7555
IGN: Awesome_Boy

**Comment by Awesome-Boy-001** [comment]
Simplified Chinese language adds/updates have submitted in Pull Request: https://github.com/mty22/krunker.io-translations/pull/82
