### ISSUE TITLE
Review French language state

### ISSUE THREAD

**Issue by mty22** [mty22/krunker.io-translations#337]
A member of the community sent me a DM providing some examples of potential incorrect translations within `fr.js` file.

**Comment by mty22** [comment]
exert:
```windows.loadout.wrist is not translated in game (should be Poignet
windows.loadout.face should be Visage (current one means head)
windows.loadout.hat would be more suiting as Tête (head for head items)
windows.melee.header should be Arme de mêlée, accorded to Arme principale and Arme secondaire on the same window```

**Comment by mty22** [comment]
Need to form a group/team and review https://github.com/mty22/krunker.io-translations/blob/main/fr.js for consistency.

**Comment by mty22** [comment]
Minimum 3 people.

**Comment by enygmate** [comment]
OK let's do this, I should have some free time ahead tomorrow so I should be able to work on it.

**Comment by Kason19** [comment]
> Minimum 3 people.
I would like to help if i can. Even though I might just be random, i'm a native speaker.

**Comment by enygmate** [comment]
It'd be great! I saw your PRs and they're all good

**Comment by mty22** [comment]
Sorted in #390 

Thanks everyone!
