### ISSUE TITLE
Proposing to change Tagalog (tg.js) to Filipino (fil.js)

### ISSUE THREAD

**Issue by Navsy17** [mty22/krunker.io-translations#347]
Background Info:

Minecraft officially uses 'Filipino' as one of their language options
Google Services recognizes if you use 'Filipino'
The academic subject according to the curriculum is 'Filipino'
Wikipedia has a differentiation of 'Filipino' and 'Tagalog'

It may be hard to understand at first, but majority of 'Filipino' are Tagalog words. If it were pure Tagalog and not Filipino, we wouldn't have mixed English and Spanish words in them.

Crazy though, since there are many debates outside of Krunker regarding this and a lot of misconceptions occur.

**Comment by mty22** [comment]
https://github.com/mty22/krunker.io-translations/blob/main/languages.js#L18

likely falls in a bigger thing to change all of them to standardise:

https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by Navsy17** [comment]
> https://github.com/mty22/krunker.io-translations/blob/main/languages.js#L18
> 
> likely falls in a bigger thing to change all of them to standardise:
> 
> https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

if thats the case, we're fine with the standardized fil

**Comment by mty22** [comment]
Still on the agenda.

**Comment by Navsy17** [comment]
Thanks a lot, will try to contact P4YGE in the meantime.

**Comment by mty22** [comment]
I don't think there will be any movement on this one unfortunately.
