### ISSUE TITLE
Dutch language support (v3.8.1)

### ISSUE THREAD

**Issue by mty22** [mty22/krunker.io-translations#35]
Discord user `Semliot#0070` reached out to me asking about Dutch translations.

Need to check feasibility on this before going ahead.

**Comment by AdoreMe-GitHub** [comment]
I would like to translate to Dutch aswell since i'm a native speaker.
Discord user: `AdoreMe#0082`

**Comment by Semliot** [comment]
> I would like to translate to Dutch aswell since i'm a native speaker.
> Discord user: `AdoreMe#0082`

I've talked to AdoreMe and we are going to translate it together.

**Comment by gluzly** [comment]
I would love to help translate to Dutch aswell. I'm from the Netherlands myself and fluent in Dutch, and I'm almost fluent in English, so this could help me with that :)

**Comment by mty22** [comment]
Dutch is approved. @Semliot

**Comment by Semliot** [comment]
> Dutch is approved. @Semliot

Alright we will start working on this as soon as possible.

**Comment by crumb8040** [comment]
Can I contribute? I'm a native Dutch speaker

**Comment by jasperdz** [comment]
I am also a native Dutch speaker (Belgian origin) and i would love to participate!
[ Discord: `JASPER.DZ#1541` ]

**Comment by mty22** [comment]
@crumb8040 @jasperdz sure - reach out to @Semliot and check with him on his progress. He may have finished already.

Keep an eye out in Discord, I'll be posting an update to all the files for v3.8.2 patch soon.
