### ISSUE TITLE
Issue with Turkish Letters

### ISSUE THREAD

**Issue by SecretMember** [mty22/krunker.io-translations#363]
![image](https://user-images.githubusercontent.com/42272891/154698981-029f0ec4-903f-4bef-a00c-15ab207df154.png)
It is supposed to look like ''BAĞLANTI KESİLDİ''. Ğ and capital i (İ) are not visible.

**Comment by mty22** [comment]
Referenced in https://github.com/mty22/krunker.io-translations/blob/b49314d1a63203aa1f201e031aaced424e67cf2c/KNOWN_ISSUES.md

**Comment by mty22** [comment]
@SecretMember feel free to revert those specific letters to English, or revert  the word its self back to English (which ever makes more sense) !
