### ISSUE TITLE
Hindi Translation of Krunker (v3.8.1)

### ISSUE THREAD

**Issue by Rishabh4Jakhar** [mty22/krunker.io-translations#37]
I am Indian and I feel I can help in translating krunker into hindi (main language of India)

**Comment by Millionword** [comment]
i can review as well

**Comment by mty22** [comment]
Hi @Rishabh4Jakhar and @Millionword - There's an active pull request currently in a review state pending to be merged:

https://github.com/mty22/krunker.io-translations/pull/17
