### ISSUE TITLE
Italian Language translation help

### ISSUE THREAD

**Issue by Wefflay** [mty22/krunker.io-translations#39]
Hi!I would like to help translating the game,to italian.
Since its my main language and I studied it a lot,i could help a lot,also for the grammar,that i see tons of people misspell/do wrong.
I have a lot of translation experiences and I know english language a lot!
I would love to help translating!
discord user just in case: Waffley#7335

**Comment by mty22** [comment]
Hi @Wefflay -- This is a duplicate issue of https://github.com/mty22/krunker.io-translations/issues/25

Check it out please~
