### ISSUE TITLE
I can translate Krunker to Bahasa Melayu or Chinese

### ISSUE THREAD

**Issue by EeYoungDad** [mty22/krunker.io-translations#395]
I am a native speaker of Chinese, English and Bahasa Melayu since lots of Malaysian is joining krunker, I am able to speak and write in Malay or Chinese. If I get approval, I can get to work right away. Discord tag : EeYoungDad#7348 Krunker IGN : EeYoungDad

**Comment by mty22** [comment]
see https://github.com/mty22/krunker.io-translations/issues/76
