### ISSUE TITLE
Hello! I am looking to translate the game!

### ISSUE THREAD

**Issue by athyze-krunker** [mty22/krunker.io-translations#404]
Hello!

(About translating swedish)

"Keep in mind that in order to be eligible for KR payouts, the language must be approved first. With that being said, you are still welcome to translate it although it won't be added to the game." - @mty22

Hello, just to clarify. Would it still be okay if I translated the game and didn't receive anything and the translations most likely wont be added to the game?

**Comment by mty22** [comment]
You can translate into Swedish if you wish, however it won't be compensated as it's not a language in scope at this time.
