### ISSUE TITLE
Krunker Latvian translation

### ISSUE THREAD

**Issue by WHITEwingTTV** [mty22/krunker.io-translations#405]
Hey im WHITEwing or just Matt, ive always wanted krunker to have my national language -Latvia. I am a 14yo student from Latvia, Cēsis and i can translate this language perfectly since i know this language since i was born and living in a family where every way of this language has been used. Latvia is one of three countries in the baltics (part of europe) with a population under 2 million but our language is one of the richest and its very buetiful.

(google translate can translate this language but not perefectly making grammatical errors once in a while hats why i can help)

**Comment by mty22** [comment]
Hello,

Thanks for the interest. If we see more push for Latvian, then we'll reach out to you!

Cheers.
