### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by 010Filip010** [mty22/krunker.io-translations#41]
Hello,
I'd like to help out with translating krunker into polsih.It's my main language and I have a lot of expierience with it. I lived abroad for 12 years in an english speaking country so i am expierienced with it too. My discord is filip010#3537

**Comment by mty22** [comment]
Hi @010Filip010 

we have an active pull request for Polish already - feel free to have a look and review! https://github.com/mty22/krunker.io-translations/pull/24/
