### ISSUE TITLE
I am a mainland Chinese, I am familiar with English and Chinese, if I get the approval, I can start working immediately. I can do translations in Krunker Market

### ISSUE THREAD

**Issue by Freddyxia** [mty22/krunker.io-translations#419]

**Comment by Freddyxia** [comment]
Chinese (Simplified）

**Comment by mty22** [comment]
@0v0katai can you please speak with @Freddyxia and go over the submission and review process? :) close when read.

**Comment by DevChrisChan** [comment]
Hey - can I contribute for Chinese and Chinese Traditional too? Please DM me on ItsChris#0001. Looking forward to help 😄

**Comment by mty22** [comment]
See my above comment too, thanks!
