### ISSUE TITLE
Hebrew Translation

### ISSUE THREAD

**Issue by Preemey** [mty22/krunker.io-translations#42]
Hey! Hebrew is my Native language and I would like to help translate the game! Discord: Mareeo#8227

**Comment by mty22** [comment]
Hi, I've also had a few people DM me directly on Discord in regards to Hebrew language.

I'll review it and get back to you.

**Comment by mty22** [comment]
Hello, thank you for the offer. While you're welcome to translate Krunker into Hebrew, we won't be adding it to the game anytime soon.

Check out the README file (https://github.com/mty22/krunker.io-translations/blob/main/README.md), specifically this:

```
Languages worked on without approval will still likely be accepted, although it may not be added to the game. We will keep a copy of the language on this git repository for future use. If it is added to the game, we'll reach out to the person who submitted the pull request, and compensate accordingly!
```

Cheers.
