### ISSUE TITLE
Translating krunker to estonian.

### ISSUE THREAD

**Issue by erkkiretu** [mty22/krunker.io-translations#423]
Hi! Is there chance that i can translate krunker to estonian?

**Comment by erkkiretu** [comment]
I would like to add estonian language, because im pretty sure theres Estonian players too (ex. me), so it would be nice that there's estonian language too. If your interested then my dms are open (z1#8937)

**Comment by mty22** [comment]
Will pass on this one for now sorry, thanks for the interest though!
