### ISSUE TITLE
Greek translating in krunker

### ISSUE THREAD

**Issue by Aeroblade727** [mty22/krunker.io-translations#43]
Hello! I am a native greek speaker and am fluent in english and have had experience in translating previously. If anyone is interested message at my discord Aeroblade#9241

**Comment by mty22** [comment]
Hello, thank you for the offer. While you're welcome to translate Krunker into Greek language, we won't be adding it to the game anytime soon.

Check out the README file (https://github.com/mty22/krunker.io-translations/blob/main/README.md), specifically this:

```
Languages worked on without approval will still likely be accepted, although it may not be added to the game. We will keep a copy of the language on this git repository for future use. If it is added to the game, we'll reach out to the person who submitted the pull request, and compensate accordingly!
```

Cheers.
