### ISSUE TITLE
can translate english to french

### ISSUE THREAD

**Issue by Le-skal** [mty22/krunker.io-translations#432]
hello, I am a french student but I have lived for 14 years in an international country (hong kong) where the main spoken language is English. As a result, shortly after arriving in hong kong, I switched from the french section to the international section where I am currently studying for my IB's. Anyways, I am fully fluent in English and hope my french knowledge can help.

Bonjour, je suis un etudiant francais qui deuis 14 ans habite a l'international (a hong kong) ou la langue parle est principalement l'anglais. pas consequent, en arrivant a hong kong, j'ai rapidement change de section pour suivre un cursus anglais afin de fair mon ib et dans le future pouvoir voyage a l'international. bref, je suis capable de parle anglais et francais parfaitement, et j'esepre pouvoir vous aider.

Bien a Vous.
Le_skal#3528 (<--discord)

**Comment by mty22** [comment]
Reach out to the existing community in Krunker Bunker. 

https://github.com/mty22/krunker.io-translations/blob/main/CONTRIBUTORS.md

Feel free to collaborate with them!
