### ISSUE TITLE
Translating English to Russian

### ISSUE THREAD

**Issue by FlawlessKai** [mty22/krunker.io-translations#434]
I am a native Ukrainian speaker, and Russian is very close to the Ukrainian language. I can speak fluent Russian, and have many other people in my life ask me to translate Russian for them. I am currently in America, and can speak fluent English as well. I have a lot of experience with translation. I could be the perfect addition for Russian translation.

**Comment by Kxlici** [comment]
mty just moved to a new place so he can't approve rn wait for like 2 weeks

**Comment by FlawlessKai** [comment]
k no problem

**Comment by mty22** [comment]
go for it!

**Comment by FlawlessKai** [comment]
Thx :)
