### ISSUE TITLE
english to spanish

### ISSUE THREAD

**Issue by SCycle** [mty22/krunker.io-translations#435]
Spanish is my primary language, I am very fluent in it. I think I would be a good fit for the Spanish translation.

**Comment by johnaccardi** [comment]
Spanish is my first language, and I lived in UK (England) for 5 years and I also lived in New York for 2 years, i think I could translate it with any problem, also I got the time and the experience.

**Comment by mty22** [comment]
Yes. Reach out to the respective Spanish contributors for assistance if required 

https://github.com/mty22/krunker.io-translations/blob/main/CONTRIBUTORS.md#spanish-espa%C3%B1ol
