### ISSUE TITLE
Translating Krunker to Filipino

### ISSUE THREAD

**Issue by P4YGE** [mty22/krunker.io-translations#438]
Hello, my ign in krunker is _PAYGE_, I am an average player with a level of 58 and have a 16d 6h 9m of playtime when I'm creating this application.

I am a Filipino and live in the Philippines, my primary language is called Filipino, not Tagalog because the official name for the Philippine national language is Filipino, not Tagalog. And in fact, "Filipino" means Philippine citizen too. The 2nd most used language in the Philippines is English, I am very fluent in speaking Filipino and English.

I want to join the krunker translators because I want to be part of the developer team of the game. And help them by correcting the Filipino language that has an error such as wrong spelling and wrong grammar. By doing this, I'm helping my fellow Filipino krunker players too who have an issue in understanding English or reading the English language, by making the game understandable according to the language they can comprehend.

Hopefully, you choose me as a part of the krunker translators.

**Comment by Navsy17** [comment]
@P4YGE We also proposed on changing 'Tagalog' to 'Filipino' a few months back, it seems that it won't be done any soon, in the mean-time, can I have your Discord Tag and name in Krunker Bunker so we can communicate?

**Comment by Navsy17** [comment]
Also please refer to #347 so we can talk there regarding changing 'Tagalog' to 'Filipino'
