### ISSUE TITLE
Polish Translation Request

### ISSUE THREAD

**Issue by Dedazen** [mty22/krunker.io-translations#44]
Hi, I am opening this issue because I am interested in creating a Polish translation for the game.  Please feel free to contact me.

**Comment by smokjab** [comment]
I am willing to help. my discord is smokjab#1200

**Comment by NotKatsuro** [comment]
Same here, my discord is NotKatsuro | Don't#0001

**Comment by xhg4** [comment]
I'd be willing to help although it seems like somebody has already done a Polish translation and it's in the "pull requests" tab and it's waiting for approval. Also, it seems like it hasn't been yet reviewed by a native

Either way, my discord is xhg4#5231 and I'm a native Polish speaker

**Comment by mty22** [comment]
Hi everyone,

We have an active pull request for Polish already - feel free to have a look and review! https://github.com/mty22/krunker.io-translations/pull/24/
