### ISSUE TITLE
Translating Krunker to Serbian

### ISSUE THREAD

**Issue by 5koNajjaci** [mty22/krunker.io-translations#443]
I want to translate Krunker to Serbian so players from my country can have more fun and read their language while playing Krunker. Many people from my country don't understand English so I want to help them. I am 26 years old Serbian who likes video games and helping people.

**Comment by mty22** [comment]
Thanks for the interest! for now we will hold off on Serbian.

https://github.com/mty22/krunker.io-translations/issues/47
