### ISSUE TITLE
Romanian translation for Krunker.io

### ISSUE THREAD

**Issue by cheesecake489** [mty22/krunker.io-translations#45]
Hello,I can help with the translation process.I am from Romania.My discord is:Cheesecake#6728. Quick edit:My friend TrainerGabe#9381 and I decided that we should do it together,he posted hes issue above.

**Comment by cheesecake489** [comment]
For some reason GitHub doesnt allow me to put a normal zero after the hashtag so i just wrote them like that :|

**Comment by mty22** [comment]
dupe https://github.com/mty22/krunker.io-translations/issues/50
