### ISSUE TITLE
Translating into Hungarian (v3.8.1)

### ISSUE THREAD

**Issue by Kmiki07** [mty22/krunker.io-translations#46]
I am able to translate the full game / website to Hungarian.
My IGN: Kmiki007
My discord: Kmiki007#5307

**Comment by Kmiki07** [comment]
Translation done, pending review

**Comment by mty22** [comment]
Can you please submit a pull request, then link this issue to the pull request? 

![image](https://user-images.githubusercontent.com/2951231/115031801-ec216400-9f0b-11eb-9806-7078b38613bc.png)

I'll still need to review/approve it before it's merged as it may not be a language in focus.

Thank you for acting so fast though. :)

**Comment by barnakdaniel** [comment]
> Can you please submit a pull request, then link this issue to the pull request?
> 
> ![image](https://user-images.githubusercontent.com/2951231/115031801-ec216400-9f0b-11eb-9806-7078b38613bc.png)
> 
> I'll still need to review/approve it before it's merged as it may not be a language in focus.
> 
> Thank you for acting so fast though. :)

Is there a way I can apply for reviewing the translation? I am a native hungarian speaker who speaks fluent english aswell.
