### ISSUE TITLE
Arabic translation

### ISSUE THREAD

**Issue by asumait11** [mty22/krunker.io-translations#461]
Hello, I'm an Arabic native speaker and also speak English fluently, I almost ended my Arabic translation and it's only me who works on that, anyway, My translation is getting checked by 
an Arabic professional that I paid to do that, so it doesn't have to get reviewed by a native, how long will it take to finish everything and add it to the game?
Kind regards, 
Abdallah Sumait

**Comment by mty22** [comment]
No to arabic, see https://github.com/mty22/krunker.io-translations/issues/2
