### ISSUE TITLE
Serbian/Croatian/Bosnian Translation for block game.

### ISSUE THREAD

**Issue by MilanSCR** [mty22/krunker.io-translations#47]
Almost the whole of Balkans speak the same language and I think Croatian/Bosnian would work the best here since it's not Cyrillic and more people can read it, rather than going with Serbian which is written like rUsSiaN letters.

![image](https://user-images.githubusercontent.com/82604982/114909196-2c55e900-9e1d-11eb-8e9f-ed28ad5e61f6.png)
Most of these countries can understand/speak the same language so I could help a lot with this :)

![image](https://user-images.githubusercontent.com/82604982/114910404-28769680-9e1e-11eb-9c63-83e5ffa84bd3.png)

**Comment by MilanSCR** [comment]
closed by accident were good boys

**Comment by MilanSCR** [comment]
So far I've translated about 350 lines to Croatian we're boolin' on Mars boys.

**Comment by mty22** [comment]
lol, nice.

I haven't given approval, but thank you for translating what you've done so far.

Feel free to submit a pull request if you wanted to submit what you've done so far.

**Comment by prljav** [comment]
@MilanSCR treba pomoc?
