### ISSUE TITLE
Translating to Vietnamese

### ISSUE THREAD

**Issue by Flair74** [mty22/krunker.io-translations#48]
i'm gonna translate the krunker blocc game with guns to Vietnamese, discord Flair#7505

**Comment by mty22** [comment]
Hello, thank you for the offer. While you're welcome to translate Krunker into Vietnamese language, we won't be adding it to the game anytime soon.

Check out the README file (https://github.com/mty22/krunker.io-translations/blob/main/README.md), specifically this:

```
Languages worked on without approval will still likely be accepted, although it may not be added to the game. We will keep a copy of the language on this git repository for future use. If it is added to the game, we'll reach out to the person who submitted the pull request, and compensate accordingly!
```

Cheers.
