### ISSUE TITLE
Krunker to Romanian

### ISSUE THREAD

**Issue by 120452** [mty22/krunker.io-translations#486]
Hi. Im a native Romanian dude and I would love to translate Krunker into this language, cuz I know many friends who are playing this game in their freetime and also I just love Krunker...

I speak English fluent and I hope I can be of some use for expanding Krunker into my country as well :D

IGN: Nemex
Discord: Nemex#6752

**Comment by mty22** [comment]
Hello thank you for the interest, however for now we won't be adding Romaian to the game.

you are welcome to add it as a WIP Language without compensation.

https://github.com/mty22/krunker.io-translations/issues/50
