### ISSUE TITLE
Translating into Traditional Chinese (v3.8.1)

### ISSUE THREAD

**Issue by inv10498** [mty22/krunker.io-translations#49]
Going to take a shot at translating Krunker into Traditional Chinese, might be helpful for players from Hong Kong, Taiwan, etc. I will be working with searinsin#7965, my discord tag is inv#6091. Feel free to reach out if you want to work us, the more the merrier.

**Comment by mty22** [comment]
Discord user `vl#5058` also sent me a message a few days ago asking about this.

Will review.

**Comment by WpyGG4125** [comment]
Have just completed the translation, I'll also be available for anything necessary

**Comment by mty22** [comment]
This is approved.
