### ISSUE TITLE
Romanian translation (v3.8.1)

### ISSUE THREAD

**Issue by TrainerGabeKR** [mty22/krunker.io-translations#50]
Hi, me and Cheesecake would like to begin working on Romanian. Im a native Romanian speaker and writer, and can definitely work on the project. Cheesecake is also Romanian and wishes to work on the project. Could a file be opened up for Romanian so we may work on the project? 

My Discord: TrainerGabe#9381
Cheesecake's: Cheesecake#6728

**Comment by cheesecake489** [comment]
Yes please 😛

**Comment by mty22** [comment]
Hi,

Will get back to you on this one. Need to check feasibility on this.

**Comment by cheesecake489** [comment]
Alright

**Comment by mty22** [comment]
I still need to find out player statistics to see if its feasible to translate Krunker into Romanian language.

**Comment by mty22** [comment]
We'll hold off on Romanian for now, I'll ping you if we wish to add it in future - thank you!
