### ISSUE TITLE
Romanian Krunker

### ISSUE THREAD

**Issue by DariusDuracell** [mty22/krunker.io-translations#501]
Hello! I am a native Romanian speaker and I have been playing a lot lately. I have also seen friends of mine starting to play it but they aren't the best at english and had trouble reading some stuff. I decided that if i would try and succeed translating Krunker in romanian, I would help my friends and also other romanian people.

**Comment by mty22** [comment]
Please see: https://github.com/mty22/krunker.io-translations/issues/50
