### ISSUE TITLE
Swedish translation for Krunker

### ISSUE THREAD

**Issue by theoliveboiii** [mty22/krunker.io-translations#504]
Hello krunker team,

I am opening this issue because I would like to create Swedish translation for krunker. I thought it was a good idea because I see allot of Swedish players while playing the game and I thought it would help some of the Swedes that don't understand english. I have lived in Sweden my whole life and am fluent in the language. Another reason i would like to do it is because right now I thought it would be fun, I got even more motivation to do it when i saw the rewards for doing it.  I do not want any help with doing it but if i need to have a partner I'll try to get someone else with me. I know you have already declined somebody elses offer but i thought i would bring the thought up again. I would really apriciate doing it. Even if you do not accept I would apriciate if i got given reasoning to why you wouldn't like a Swedish translation. 

Please reach out to me via discord via this issue, tag me on Krunker bunker or send a direct message: the olive#4921

**Comment by mty22** [comment]
Hello @theoliveboiii 

According to Wikipedia(https://en.wikipedia.org/wiki/List_of_countries_by_English-speaking_population), 89% of the population in Sweden can speak in English.

Unfortunately it does not make sense to translate the game into Swedish.

**Comment by theoliveboiii** [comment]
> Hello @theoliveboiii
> 
> According to Wikipedia(https://en.wikipedia.org/wiki/List_of_countries_by_English-speaking_population), 89% of the population in Sweden can speak in English.
> 
> Unfortunately it does not make sense to translate the game into Swedish.



> Hello @theoliveboiii
> 
> According to Wikipedia(https://en.wikipedia.org/wiki/List_of_countries_by_English-speaking_population), 89% of the population in Sweden can speak in English.
> 
> Unfortunately it does not make sense to translate the game into Swedish.

When I was referring to the people who couldn’t speak English I was referring to all the kids that play the game, but thanks for telling me why. I would like to do some other translation to help out with this project, thou I still don’t understand why there is more reason to having a Finish translation more than a Swedish one. I would also like to help out in this project with finish and spanish translation but I’ll create another issue I decide to do so.

**Comment by mty22** [comment]
Finnish language is considered as legacy (maintained).

If for example, Finnish wasn't in the game and a user requested; it would not be added due to the same reasons as above.

**Comment by theoliveboiii** [comment]
> Finnish language is considered as legacy (maintained).
> 
> If for example, Finnish wasn't in the game and a user requested; it would not be added due to the same reasons as above.

Ok, thank you for clarifying.
