### ISSUE TITLE
Translating into Turkish (v3.8.1)

### ISSUE THREAD

**Issue by hon0urdy** [mty22/krunker.io-translations#51]
Im going to try translating it in Turkish.Im going to work with W_O#1903 and my discord tag is hon0urdy#5024.

**Comment by KenTechYT** [comment]
I'd love to help, I speak fluent Turkish. Discord: KenTech#6969

**Comment by mty22** [comment]
ty, I will look into it~

**Comment by KenTechYT** [comment]
Alright, thanks!
