### ISSUE TITLE
Krunker translation into Swedish (v3.8.1)

### ISSUE THREAD

**Issue by ShishKebob6570** [mty22/krunker.io-translations#52]

**Comment by mty22** [comment]
Hi @ShishKebob6570 - please wait for approval before commencing.

**Comment by mty22** [comment]
``` IGN: Bokmalen, skit_gubben, ErikKR || My Disc: NiroKR#1942```
^ just capturing this.

**Comment by ShishKebob6570** [comment]
Hi, 
When is my issue going to be approved?
Thanks,
NiroKR

**Comment by ShishKebob6570** [comment]
And btw now ErikKR has opted out of the project.

**Comment by mty22** [comment]
Hello,

for now - we will hold off on translating Krunker into Swedish.

thank you for the interest!

**Comment by ShishKebob6570** [comment]
Does this mean Swedish will be a future language possibly? That too, I'll just send this thread to the others. 
(We are 13 yrs old btw :D )

**Comment by ShishKebob6570** [comment]
No problem!

**Comment by Superattiz** [comment]
maybe i could help with the swedish translation?
