### ISSUE TITLE
Translation to Slovenian 

### ISSUE THREAD

**Issue by Yusufiv** [mty22/krunker.io-translations#520]
Hello there,

I am an English speaker from the UK with a knack of learning new languages. Slovenian is one of the languages I know. I want to get an approval for translating Krunker.io into Slovenian.

Many thanks,
Yusuf

**Comment by Yusufiv** [comment]
Hello,

 I have just noticed that a Slovenian translation is already in development.

Please let me know if there are any urgent languages needed to be translated. Me and my associates  have experience in many other languages.

Best Regards,
Yusuf

**Comment by blablakali** [comment]
Urdu?

**Comment by Yusufiv** [comment]
I don’t know enough Urdu. But my friend Ibrahim has a degree for teaching Urdu. He is available to help me. If have an approval for Urdu I will start translation immediately.

**Comment by Yusufiv** [comment]
#171 

Sorry,
Just a quick update I look through the issues and have seen that Krunker does not support languages written from left to right.

However I am willing to develop a script that supports those types of languages if I get approval.
