### ISSUE TITLE
I can translate Krunker to Serbian

### ISSUE THREAD

**Issue by M4vm** [mty22/krunker.io-translations#56]
Hello,

Ive been learning English for over 10 years now and I would like to help the community by translating the game to Serbian , because a lot of people in Serbia dont know English very well.

My Discord username is: M4vm#4787

**Comment by mty22** [comment]
Nice, please let me review this and get back to you.

**Comment by MilanSCR** [comment]
@M4vm I'm pretty much done with Croatian and you could help me out with polishing it since Serbian and Croatian are esentially the same language.

**Comment by mty22** [comment]
Sorry for the delay. We will hold off on this language for now. If we add it in future, we'll re-open this thread.

This doesn't mean you aren't able to translate into your respective, it just means that the language is not likely to be added and you wouldn't be eligible for KR rewards (unless approved).
