### ISSUE TITLE
Slovenian Translation of Krunker

### ISSUE THREAD

**Issue by Basketboss23** [mty22/krunker.io-translations#57]
Greetings!
I, IG5K, and Kekec would like to begin working on the Slovenian translation. We are all born in Slovenia and all of us are in Highschool. IG5K has a diploma in Slovene and can definitely work on the project. We have all been playing this game for more than a year and a half and 2 of us have a level +110 account. I own a YouTube Channel with +360 subscribers. So we are really serious about the game.

Slovenian language is the complete opposite of English so it would be nice to have it translated. We've all been studying English for more than a decade, so we will have no problems.

We would love to begin with the translation.

My Discord: `Basketboss23#0723`............IGN: Basketboss23
IG5K's: `IG5K#7389` ........................................IGN: IGot5Killzz
Kekec's: `Kekec#0004`....................................IGN: 8uraz

**Comment by Basketboss23** [comment]
We have decided to translate the entire thing anyway, even though we didn't get the approval, because we found it fun.  We can Submit a Pull request if you want.
@mty22 
We are looking forward to your response!

**Comment by mty22** [comment]
@Basketboss23 feel free to submit a PR. I am going to adjust the structure of how this works with languages aren't approved yet. :)
