### ISSUE TITLE
Krunker translation Nepali

### ISSUE THREAD

**Issue by Millionword** [mty22/krunker.io-translations#58]
I would like to translate drunker into Nepali. I was originally born in Nepal and i can translate it into Nepali. Nepali is similar to Hindi but it has enough differences that if you were to say something in Hindi, it would not make a lot of sense to people who speak or read Nepali. It's sort of like french and English. They both have similar words, but both have differently structured sentences, etc. I can also understand hindi and translate that as well, and to a lesser degree, i can translate bangla. 
discord is klamspy#4376

**Comment by Millionword** [comment]
Yup

**Comment by mty22** [comment]
Hi,

Thanks for the request - for now, we will wait for Hindi to be merged (in PR: https://github.com/mty22/krunker.io-translations/pull/17)

Once that's done, we'll gauge community feedback and reach out to you if needed to start on Nepali.
