### ISSUE TITLE
Krunker translation Khmer

### ISSUE THREAD

**Issue by Sandveech** [mty22/krunker.io-translations#61]
I'd would like to translate krunker into Khmer. My original birth place is Cambodia and I can translate English into Khmer. Khmer has borrowed words from other South East Asian like Thai or Lao, there will be different words if put in a translator but it'll make sense to the people who speak Khmer.
discord:
![image_2021-04-16_115551](https://user-images.githubusercontent.com/82623509/114973443-b13b1400-9eaa-11eb-8dc5-51e5166d8703.png)

**Comment by mty22** [comment]
Hello, thank you for the offer. While you're welcome to translate Krunker into Khmer language, we won't be adding it to the game anytime soon.

Check out the (README)[https://github.com/mty22/krunker.io-translations/blob/main/README.md] file, specifically this:

```
Languages worked on without approval will still likely be accepted, although it may not be added to the game. We will keep a copy of the language on this git repository for future use. If it is added to the game, we'll reach out to the person who submitted the pull request, and compensate accordingly!
```

Cheers.
