### ISSUE TITLE
Krunker Translation to Thai

### ISSUE THREAD

**Issue by ChanwishLi** [mty22/krunker.io-translations#65]
Hi
I would like to translate krunker to Thai. I have a group of friends who like to play krunker, we can all speak English and we are all Thai. I got intrested in this project because Krunker is kinda popular in Thailand, so I want to translate some stuff. I am confident I can do it because I've taken the Tofel test 2 times and the results were great, so I think I could do some translation.

My Discord: chanLi#5947
:)

**Comment by 8-10krunker** [comment]
Id like to help with Thai too. I learned a bit of Thai and have siblings that can speak it. my discord is: 8-10#4197
:}

**Comment by mty22** [comment]
Sorry for the delay. We will hold off on this language for now. If we add it in future, we'll re-open this thread.

This doesn't mean you aren't able to translate into your respective, it just means that the language is not likely to be added and you wouldn't be eligible for KR rewards (unless approved).
