### ISSUE TITLE
Krunker translation to Hindi

### ISSUE THREAD

**Issue by BOTMAN07** [mty22/krunker.io-translations#66]
Hi, I am living in India since birth and know Hindi quite fluently. I can easily translate English world to hindi without any errors or flaws. I want to contribute to krunker being translated to Hindi
discord tag:  BOTTOM#1011

**Comment by mty22** [comment]
Hi, there's currently an active pull request for Hindi. Can you please reach out to the current contributors and ask if they need assistance?

Thanks!
