### ISSUE TITLE
Krunker Translation to Malayalam

### ISSUE THREAD

**Issue by smolbruhther** [mty22/krunker.io-translations#68]
Hello,
I am an Indian who was born and brought up speaking Malayalam for the majority of my life. Being a native of my state, I know a lot of people who have trouble reading English. A translation to Malayalam would greatly help the Malayalam speaking player base in Krunker.
I have been learning English for more than **15 years** and use it professionally every day.
I have also been playing Krunker daily for almost a year now and have a level 70+ account
I would love to get approved so I could immediately begin on the Translation.

Discord: Crying#6715

**Comment by mty22** [comment]
Hello! Thank you for the request.

For now, we will wait for Hindi translation to be merged in and gauge community feedback.

Please check out this pull request: https://github.com/mty22/krunker.io-translations/pull/17

**Comment by uvaizfaisel** [comment]
> Hello,
> I am an Indian who was born and brought up speaking Malayalam for the majority of my life. Being a native of my state, I know a lot of people who have trouble reading English. A translation to Malayalam would greatly help the Malayalam speaking player base in Krunker.
> I have been learning English for more than **15 years** and use it professionally every day.
> I have also been playing Krunker daily for almost a year now and have a level 70+ account
> I would love to get approved so I could immediately begin on the Translation.
> 
> Discord: Crying#6715

can I join your team as reviewer , I would be very happy to help !!
