### ISSUE TITLE
Japanese translation fixes / new items to translate

### ISSUE THREAD

**Issue by mty22** [mty22/krunker.io-translations#7]
From:  https://krunker.io/social.html?p=profile&q=Saladacchi

```
stats page:

壁抜き wallbangs
拳キル beatdowns
近接キル melee (kill)
ニューク nukes

〇人が視聴中 streaming now

ゲームタイトルを隠す hide game title

K/Dカウンターを表示 show K/D counter
反射品質 reflection quality

easy fix:

windows.store.unboxed 〇〇さんが以下のアイテムを獲得しました 
windows.store.voucherinfo 配信やイベントのクーポンを入力する
```

**Comment by mty22** [comment]
https://github.com/mty22/krunker.io-translations/commit/fb0be0af631306a2eaf15e3a9271fa5c32460657
https://github.com/mty22/krunker.io-translations/commit/4979f3b0624428a63d089433cd4f12be4d81f4a2

**Comment by mty22** [comment]
Haven't had time to do this yet. Anyone can pick it up.

**Comment by Hiro527** [comment]
I will translate :)

**Comment by mty22** [comment]
![image](https://user-images.githubusercontent.com/2951231/113538259-20e50f80-961e-11eb-85b1-83455d2d5114.png)

https://github.com/mty22/krunker.io-translations/blob/main/jp.js#L67

「次のラウンドまであと○○秒」の方がいい？

**Comment by Hiro527** [comment]
It's correct in Japanese but I think 「次のラウンドまであと〇〇秒」is better than 「次ラウンドまであと〇〇秒」.

**Comment by Hiro527** [comment]
Should I remain this in english?
![image](https://user-images.githubusercontent.com/40311688/113538744-fd6a9680-9616-11eb-8456-8575b03c44cb.png)
https://github.com/mty22/krunker.io-translations/blob/main/jp.js#L63

**Comment by mty22** [comment]
> Should I remain this in english?
> ![image](https://user-images.githubusercontent.com/40311688/113538744-fd6a9680-9616-11eb-8456-8575b03c44cb.png)
> https://github.com/mty22/krunker.io-translations/blob/main/jp.js#L63

Yes, we'll keep that one in English.
