### ISSUE TITLE
Krunker translation to Tagalog (v3.8.1)

### ISSUE THREAD

**Issue by ran-dom9** [mty22/krunker.io-translations#71]
I have a decent amount of experience with Tagalog and I've got a friend whos a native Filipino speaker to help me with this project. Discord tag: ｒａｎｄｏｍ#0416, daje1097#1298 and astagoth#4777

Edit: another mate of mine has reached back to me saying he's up for it so I added him in here as well

**Comment by mty22** [comment]
Tagalog is approved.
