### ISSUE TITLE
I can translate Krunker to Bahasa Melayu (Malay)

### ISSUE THREAD

**Issue by kishernrao** [mty22/krunker.io-translations#76]
Ive been a native speaker of Malay and English in Malaysia, I am able to understand, speak and write in Malay. If i get approval, I can get to work right away.
discord tag: theraomaN #3383

**Comment by mty22** [comment]
`alie#0006` DM'd me with a similar request. I'll look into it but it may not be feasible at this point in time.

**Comment by mty22** [comment]
Hi, we will hold off on this for now until we have more demand for this language.
