### ISSUE TITLE
translation into traditional chinese

### ISSUE THREAD

**Issue by leviikrunker** [mty22/krunker.io-translations#78]
translation into traditional chinese would be useful for those living in hong kong, macau and taiwan as a native cantonese spesker, some people in the region cannot read simplified chinese and for others it is much easier on the eyes. other games have both traditional chinese and simplified chinese translations as well.

my discord tag is `vl#5058` and i have worked with `L.#4444` on a translation. i have previously obtained the approval of tehchy.

**Comment by mty22** [comment]
Thanks for that - there's an existing issue open for the same thing

https://github.com/mty22/krunker.io-translations/issues/49

can you reach out to those guys please?
