### ISSUE TITLE
Bulgarian translation (v3.8.1)

### ISSUE THREAD

**Issue by krunkerLover** [mty22/krunker.io-translations#81]
Hi Sid i saw you tweet and tried to translate as much as possible from English to Bulgarian 
[Krunker translation.txt](https://github.com/mty22/krunker.io-translations/files/6329727/Krunker.translation.txt)

**Comment by mty22** [comment]
Bulgarian, nice. :) Thank you for the work!

@krunkerLover can you please let me know your Krunker ingame name and Discord username as we may need to reach out to you in future.

**Comment by krunkerLover** [comment]
> Bulgarian, nice. :) Thank you for the work!
> 
> @krunkerLover can you please let me know your Krunker ingame name and Discord username as we may need to reach out to you in future.

Yeah ofc Fanta2 is my ign and OBAMA PRISM#1111 is my discord

**Comment by mty22** [comment]
We'll hold off on Bulgarian for now.
