### ISSUE TITLE
Krunker translation to spanish

### ISSUE THREAD

**Issue by avanish0** [mty22/krunker.io-translations#85]
I can speak and write very fluent Spanish and I would like to take this opportunity to help the game grow and make it accessible 
 to people in different communities speaking different languages. discord: smoke rival #8907.

**Comment by mty22** [comment]
Hi @avanish0 - thank you for this

There's an existing pull request and issue for spanish :)

https://github.com/mty22/krunker.io-translations/issues/29

Feel free to have a look at the pull request and see if you can find any problems!

Have a look and reach out if you are able to help.
