### ISSUE TITLE
Krunker albanian language

### ISSUE THREAD

**Issue by Cat3457** [mty22/krunker.io-translations#92]
I am currently translating Krunker into the Albanian language
Also its not completed but if you need the non completed file here it is:
[krunker translate on albanian.txt](https://github.com/mty22/krunker.io-translations/files/6332089/krunker.translate.on.albanian.txt)
Althought i am still gonna work on it this is what ive done so far

**Comment by mty22** [comment]
thanks! will review and get back to you.

**Comment by Cat3457** [comment]
Also its not completed but if you need the non completed file here it is
[krunker translate on albanian.txt](https://github.com/mty22/krunker.io-translations/files/6332079/krunker.translate.on.albanian.txt)
Althought i am still gonna work on it this is what ive done so far

**Comment by Cat3457** [comment]
> thanks! will review and get back to you.

Also its not completed but if you need the non completed file here it is:
[krunker translate on albanian.txt](https://github.com/mty22/krunker.io-translations/files/6332089/krunker.translate.on.albanian.txt)
Althought i am still gonna work on it this is what ive done so far

**Comment by Cat3457** [comment]
> Hey! I would like to help with this translation if possible!

Sure!

**Comment by notexos** [comment]
@Cat3457 contact me on discord please! exos#0001

**Comment by Cat3457** [comment]
> @Cat3457 contact me on discord please! exos# 0001

ok

**Comment by Cat3457** [comment]
So recently i have uninstalled discord so i cant do that anymore. Idk but i may also not continue the translation. If you know/have any other way i can contact you exept discord let me know

**Comment by notexos** [comment]
Sorry i dont have any other way of contacting you, we could talk here though, I could continue the translation that u already sent here above.

**Comment by Cat3457** [comment]
Ok we can talk here i guess

**Comment by Cat3457** [comment]
> Sorry i dont have any other way of contacting you, we could talk here though, I could continue the translation that u already sent here above.

So i actually canceled the deletion of my account so we can talk on discord, i have sent you a friend request

**Comment by mty22** [comment]
Hi all, sorry for the delay. We will hold off on this language for now. If we add it in future, we'll re-open this thread.

Until then, you're welcome to translate the game into your language, although it won't be added into the game.

**Comment by mty22** [comment]
side note, just added this lang to the WIP folder:

https://github.com/mty22/krunker.io-translations/blob/main/work-in-progress/albanian.txt

https://github.com/mty22/krunker.io-translations/blob/main/work-in-progress/sq.js
