### ISSUE TITLE
Slovak translation of krunker

### ISSUE THREAD

**Issue by HRADZ-KR** [mty22/krunker.io-translations#96]
I was born in Slovakia and could see myself translating from English to Slovak. I don't know of anyone else in this community who could help me with this task, so I will probably get started on my own, but if someone else is interested in helping me out then we can discuss who is doing which part of the translation on discord.

My discord tag: HRADZ#8643

**Comment by mty22** [comment]
Hello!

We're going to have to hold off on Slovakian language for now.

Thank you for the interest though.
