### ISSUE TITLE
Willing to contribute to the Hindi translation of Krunker

### ISSUE THREAD

**Issue by MohamedRazeen102006** [mty22/krunker.io-translations#98]
Hi, I am a native of India too and I know Hindi fluently. I am aware that there is already a pull request waiting for merge and raised this issue to say that I want to contribute to the translation in any way possible in the near future. Plus, Bengali is my mother tongue so if there would be a future translation of Bengali I would like to contribute to that as well. Thank you

**Comment by mty22** [comment]
Hello! I've linked to the existing pull request for Hindi language! Reach out to the current team working on it if you wish to help :)
