### ISSUE TITLE
Simplified Chinese Version Update Request (v3.8.1)

### ISSUE THREAD

**Issue by WpyGG4125** [mty22/krunker.io-translations#99]
At the moment I'm working on the last parts of the Simplified Chinese version, if it still available.

Native Speaker, bilingual in both Chinese and English.

Contacts
Discord: WpyGG#4125

**Comment by mty22** [comment]
Hey @WpyGG4125  -- there's an existing pull request open.

are you able to check it out, please? :)

**Comment by WpyGG4125** [comment]
Oh yeah sure @mty22

**Comment by mty22** [comment]
@WpyGG4125 OK - let me question in [Discord first](https://discord.com/channels/448194623580667916/831383180086607922/833722205635739690), then we can sort it out!
